/**
 * Device ID management.
 * Device IDs are now generated by the server and stored locally.
 */

const DEVICE_ID_KEY = "bussy-device-id"

/**
 * Get the current device ID from localStorage (returns null if not set)
 */
export function getDeviceId(): string | null {
  try {
    return localStorage.getItem(DEVICE_ID_KEY)
  } catch {
    return null
  }
}

/**
 * Save device ID to localStorage (called after server creates device)
 */
export function saveDeviceId(id: string): void {
  try {
    localStorage.setItem(DEVICE_ID_KEY, id)
  } catch {
    console.warn("localStorage unavailable, device ID not persisted")
  }
}

/**
 * Clear the device ID (for testing/reset purposes)
 */
export function clearDeviceId(): void {
  try {
    localStorage.removeItem(DEVICE_ID_KEY)
  } catch {
    // Ignore
  }
}
